# Generated by Django 3.0.4 on 2020-03-21 10:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='id',
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
