# Generated by Django 3.0.5 on 2020-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_gitlabmetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabmetrics',
            name='commits',
        ),
        migrations.RemoveField(
            model_name='gitlabmetrics',
            name='current_branches',
        ),
        migrations.RemoveField(
            model_name='gitlabmetrics',
            name='opened_issues',
        ),
        migrations.RemoveField(
            model_name='gitlabmetrics',
            name='opened_merge_requests',
        ),
        migrations.AddField(
            model_name='gitlabmetrics',
            name='key',
            field=models.IntegerField(blank=True, choices=[(1, 'opened_issues'), (2, 'opened_merge_requests'), (3, 'current_branches'), (4, 'commits')], null=True),
        ),
        migrations.AddField(
            model_name='gitlabmetrics',
            name='value',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
