# Generated by Django 3.0.4 on 2020-03-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0003_auto_20200322_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='used_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
