# Generated by Django 3.0 on 2020-02-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='last_message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
