# Generated by Django 3.0 on 2020-04-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='text_html',
            field=models.TextField(blank=True, default=None, max_length=2000),
        ),
    ]
