# Generated by Django 3.0.4 on 2020-03-11 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='admin_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dialog',
            name='last_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='last_change',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='avatar',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='avatars', width_field='width_field'),
        ),
    ]
