# Generated by Django 3.0 on 2020-02-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='avatar',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='avatars', width_field='width_field'),
        ),
    ]
