# Generated by Django 3.0.5 on 2020-05-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200508_1017'),
        ('main', '0002_auto_20200507_2109'),
    ]

    operations = [
    ]
