# Generated by Django 3.0.6 on 2020-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200531_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image_url',
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
    ]
