# Generated by Django 3.0 on 2020-04-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200408_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='image',
            field=models.ImageField(blank=True, upload_to='wiki'),
        ),
    ]
