# Generated by Django 3.0 on 2020-02-25 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dialog_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='last_change',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='last_message',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
