# Generated by Django 3.0 on 2020-03-04 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
    ]
