# Generated by Django 3.0.5 on 2020-05-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message_is_read'),
        ('main', '0002_auto_20200508_1017'),
    ]

    operations = [
    ]
