# Generated by Django 3.0.5 on 2020-05-25 19:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200517_1110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'contact')},
        ),
    ]
