# Generated by Django 3.0 on 2020-03-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_merge_20200304_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='admin_only',
            field=models.BooleanField(default=False),
        ),
    ]
