# Generated by Django 3.0.5 on 2020-04-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200408_1840'),
        ('main', '0004_auto_20200408_1721'),
    ]

    operations = [
    ]
