# Generated by Django 3.0 on 2020-04-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200408_1721'),
        ('main', '0002_auto_20200408_1840'),
    ]

    operations = [
    ]
