# Generated by Django 3.0.5 on 2020-05-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20200511_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
