# Generated by Django 3.0.5 on 2020-05-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200511_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='admin_only',
        ),
    ]
