# Generated by Django 3.0.5 on 2020-04-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20200422_1433'),
        ('main', '0005_merge_20200419_1758'),
    ]

    operations = [
    ]
