# Generated by Django 3.0 on 2020-03-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_dialog_admin_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='admin_only',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
