# Generated by Django 3.0 on 2020-03-18 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0007_auto_20200318_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='avatars',
                                             width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
