# Generated by Django 3.0.5 on 2020-04-27 20:36

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_message_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='dialog',
            name='user_dictionary',
            field=picklefield.fields.PickledObjectField(default=0, editable=False),
        ),
    ]
