# Generated by Django 3.0.4 on 2020-03-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200318_1650'),
        ('main', '0002_auto_20200311_2016'),
    ]

    operations = [
    ]
