# Generated by Django 3.0 on 2020-03-21 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0009_merge_20200321_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='avatars', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('bio', models.CharField(default="Hey there! I'm using dmess", max_length=70)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
        migrations.DeleteModel(
            name='UserSetting',
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile'),
        ),
    ]
