# Generated by Django 3.0 on 2020-03-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200321_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
