# Generated by Django 3.0.5 on 2020-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200428_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='user_dictionary',
        ),
        migrations.AddField(
            model_name='dialog',
            name='unread_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
