# Generated by Django 3.0.5 on 2020-04-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200429_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='unread_messages',
        ),
    ]
