# Generated by Django 3.0 on 2020-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200323_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='last_change',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='last_message',
        ),
        migrations.AlterField(
            model_name='dialog',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
