# Generated by Django 3.0 on 2020-04-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200326_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='wiki')),
                ('text', models.TextField(max_length=2000)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dialog')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Message')),
            ],
        ),
    ]
